-- ReAct 弱项训练的会话与固定诊断快照。
--
-- 使用 IF NOT EXISTS 是为了兼容两种数据库：
-- 1. 新空库先执行已包含这些表的 V1；
-- 2. 已有库跳过 V1 的新内容，再由本迁移补齐训练表。
CREATE TABLE IF NOT EXISTS training_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completed_at TIMESTAMP(6),
  consecutive_topic_question_count INTEGER NOT NULL DEFAULT 0,
  covered_topic_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  current_main_question_follow_up_count INTEGER NOT NULL DEFAULT 0,
  current_main_question_index INTEGER,
  current_topic_key VARCHAR(255),
  llm_provider VARCHAR(64),
  max_consecutive_questions_per_topic INTEGER NOT NULL,
  max_follow_ups_per_main_question INTEGER NOT NULL,
  max_questions INTEGER NOT NULL,
  minimum_topic_count INTEGER NOT NULL,
  question_count INTEGER NOT NULL DEFAULT 0,
  source_resume_id BIGINT,
  source_skill_id VARCHAR(64) NOT NULL,
  started_at TIMESTAMP(6),
  status VARCHAR(24) NOT NULL,
  training_id VARCHAR(36) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_training_session_training_id UNIQUE (training_id),
  CONSTRAINT training_sessions_status_check
    CHECK (status IN ('READY', 'IN_PROGRESS', 'SUMMARIZING', 'COMPLETED', 'FAILED')),
  CONSTRAINT training_sessions_counts_check
    CHECK (
      max_questions > 0
      AND max_consecutive_questions_per_topic > 0
      AND max_follow_ups_per_main_question >= 0
      AND minimum_topic_count > 0
      AND question_count >= 0
      AND covered_topic_count >= 0
      AND consecutive_topic_question_count >= 0
      AND current_main_question_follow_up_count >= 0
    )
);

CREATE TABLE IF NOT EXISTS training_topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR(255) NOT NULL,
  evidence_json TEXT NOT NULL,
  original_average_score NUMERIC(5, 2) NOT NULL,
  priority_rank INTEGER NOT NULL,
  question_count INTEGER NOT NULL DEFAULT 0,
  sample_count INTEGER NOT NULL,
  status VARCHAR(16) NOT NULL,
  topic_key VARCHAR(255) NOT NULL,
  training_session_id BIGINT NOT NULL,
  CONSTRAINT uk_training_topic_session_key UNIQUE (training_session_id, topic_key),
  CONSTRAINT training_topics_status_check
    CHECK (status IN ('PENDING', 'ACTIVE', 'COMPLETED')),
  CONSTRAINT training_topics_values_check
    CHECK (
      original_average_score >= 0
      AND original_average_score <= 100
      AND priority_rank > 0
      AND question_count >= 0
      AND sample_count > 0
    ),
  CONSTRAINT fk_training_topic_session
    FOREIGN KEY (training_session_id) REFERENCES training_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_training_session_source_created
  ON training_sessions (source_resume_id, source_skill_id, created_at);
CREATE INDEX IF NOT EXISTS idx_training_session_status_updated
  ON training_sessions (status, updated_at);
CREATE INDEX IF NOT EXISTS idx_training_topic_session_priority
  ON training_topics (training_session_id, priority_rank);
CREATE INDEX IF NOT EXISTS idx_training_topic_session_status
  ON training_topics (training_session_id, status);

COMMENT ON TABLE training_sessions IS '基于历史评估证据创建的 ReAct 弱项训练会话';
COMMENT ON COLUMN training_sessions.source_resume_id IS '历史证据筛选范围，不建立外键';
COMMENT ON COLUMN training_sessions.version IS '训练状态并发更新的乐观锁版本';
COMMENT ON TABLE training_topics IS '训练创建时固化的弱项诊断与有限历史证据';
COMMENT ON COLUMN training_topics.evidence_json IS '仅供服务端只读工具使用，不通过会话接口返回';
