-- ReAct 训练总结与总结异步任务类型。
--
-- 总结只保存服务端聚合分数和经过结构化校验的公开文字，不保存模型原始响应、
-- 单题内部评分、工具参数或思维链。
CREATE TABLE IF NOT EXISTS training_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  training_session_id BIGINT NOT NULL,
  overall_score INTEGER NOT NULL,
  completed_question_count INTEGER NOT NULL,
  covered_topic_count INTEGER NOT NULL,
  narrative TEXT NOT NULL,
  strengths_json TEXT NOT NULL,
  improvements_json TEXT NOT NULL,
  next_steps_json TEXT NOT NULL,
  topic_results_json TEXT NOT NULL,
  generated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_training_summary_session UNIQUE (training_session_id),
  CONSTRAINT training_summaries_values_check
    CHECK (
      overall_score >= 0
      AND overall_score <= 100
      AND completed_question_count > 0
      AND covered_topic_count > 0
    ),
  CONSTRAINT fk_training_summary_session
    FOREIGN KEY (training_session_id) REFERENCES training_sessions(id) ON DELETE CASCADE
);

-- V20260730 的约束只允许轮次任务。总结复用同一套可靠任务状态机，因此扩展任务类型。
ALTER TABLE training_tasks
  DROP CONSTRAINT IF EXISTS training_tasks_type_check;
ALTER TABLE training_tasks
  ADD CONSTRAINT training_tasks_type_check
    CHECK (task_type IN ('INITIAL_TURN', 'ANSWER_TURN', 'SUMMARY'));

COMMENT ON TABLE training_summaries IS '训练完成后的不可变公开总结快照';
COMMENT ON COLUMN training_summaries.overall_score IS '服务端按已完成轮次内部评分计算的整场均分';
COMMENT ON COLUMN training_summaries.topic_results_json IS '按主题聚合后的训练表现，不包含单题评分';
