-- ReAct 训练轮次与可靠异步任务。
--
-- 该迁移单独追加，避免修改已经发布的 V20260729 并触发 Flyway checksum 冲突。
CREATE TABLE IF NOT EXISTS training_turns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answered_at TIMESTAMP(6),
  completed_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL,
  action VARCHAR(32) NOT NULL,
  failure_message VARCHAR(500),
  feedback TEXT,
  internal_score INTEGER,
  main_question_index INTEGER NOT NULL,
  parent_turn_id BIGINT,
  question TEXT NOT NULL,
  reference_answer TEXT,
  status VARCHAR(24) NOT NULL,
  topic_key VARCHAR(255) NOT NULL,
  training_session_id BIGINT NOT NULL,
  turn_id VARCHAR(36) NOT NULL,
  turn_index INTEGER NOT NULL,
  user_answer TEXT,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_training_turn_turn_id UNIQUE (turn_id),
  CONSTRAINT uk_training_turn_session_index
    UNIQUE (training_session_id, turn_index),
  CONSTRAINT training_turns_action_check
    CHECK (
      action IN (
        'FOLLOW_UP',
        'REINFORCE',
        'ASK_NEW_QUESTION',
        'SWITCH_TOPIC',
        'FINISH'
      )
    ),
  CONSTRAINT training_turns_status_check
    CHECK (status IN ('WAITING_ANSWER', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT training_turns_values_check
    CHECK (
      turn_index > 0
      AND main_question_index > 0
      AND (internal_score IS NULL OR (internal_score >= 0 AND internal_score <= 100))
    ),
  CONSTRAINT fk_training_turn_session
    FOREIGN KEY (training_session_id) REFERENCES training_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_training_turn_parent
    FOREIGN KEY (parent_turn_id) REFERENCES training_turns(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS training_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  completed_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL,
  deduplication_key VARCHAR(128) NOT NULL,
  processing_started_at TIMESTAMP(6),
  retry_count INTEGER NOT NULL DEFAULT 0,
  safe_error_message VARCHAR(500),
  source_turn_id BIGINT,
  status VARCHAR(24) NOT NULL,
  task_id VARCHAR(36) NOT NULL,
  task_type VARCHAR(24) NOT NULL,
  training_session_id BIGINT NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_training_task_task_id UNIQUE (task_id),
  CONSTRAINT uk_training_task_deduplication_key UNIQUE (deduplication_key),
  CONSTRAINT training_tasks_status_check
    CHECK (
      status IN (
        'QUEUED',
        'ANALYZING',
        'RETRIEVING',
        'DECIDING',
        'GENERATING',
        'COMPLETED',
        'FAILED'
      )
    ),
  CONSTRAINT training_tasks_type_check
    CHECK (task_type IN ('INITIAL_TURN', 'ANSWER_TURN')),
  CONSTRAINT training_tasks_values_check
    CHECK (attempt_count >= 0 AND retry_count >= 0),
  CONSTRAINT fk_training_task_session
    FOREIGN KEY (training_session_id) REFERENCES training_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_training_task_source_turn
    FOREIGN KEY (source_turn_id) REFERENCES training_turns(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_training_turn_session_status
  ON training_turns (training_session_id, status);
CREATE INDEX IF NOT EXISTS idx_training_turn_session_topic
  ON training_turns (training_session_id, topic_key, turn_index);
CREATE INDEX IF NOT EXISTS idx_training_task_status_updated
  ON training_tasks (status, updated_at);
CREATE INDEX IF NOT EXISTS idx_training_task_session_created
  ON training_tasks (training_session_id, created_at);

COMMENT ON TABLE training_turns IS 'ReAct 训练问题、回答和反馈轮次';
COMMENT ON COLUMN training_turns.internal_score IS '仅供服务端策略和总结使用，不直接展示';
COMMENT ON TABLE training_tasks IS '以数据库为事实来源的训练异步任务';
COMMENT ON COLUMN training_tasks.deduplication_key IS '首题或回答任务的业务幂等键';
COMMENT ON COLUMN training_tasks.safe_error_message IS '允许前端展示的清洗后错误提示';
